spring:
  application:
    name: what2eat
  web:
    resources:
      add-mappings: false
  datasource:
    driver-class-name: ${DB_DRIVER}
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

kakao:
  rest:
    api:
      key: ${KAKAO_REST_API_KEY}
      url: ${KAKAO_STORE_API_URL}
  redirect_url: ${KAKAO_REDIRECT_URL}

logging:
  level:
    org:
      springframework: DEBUG

springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: index.html # Swagger UI 경로 => localhost:8000/demo-ui.html
  tags-sorter: alpha # alpha: 알파벳 순 태그 정렬, method: HTTP Method 순 정렬*
  operations-sorter: alpha # alpha: 알파벳 순 태그 정렬, method: HTTP Method 순 정렬*